language: python

install:
    - pip install -U pip
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - python setup.py build_ext --inplace
    - python setup.py install

before_script:
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

jobs:
    include:
        - stage: test
          name: test
          script: pytest -sv
        - stage: fossa
          # FOSSA_API_KEY unavailable for pull requests
          # https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
          if: fork = false
          name: fossa
          script:
              # NOTE: before running `fossa` make sure to save your FOSSA_API_KEY in your
              # environment variable in Travis see below.
              - fossa init
              - fossa analyze
after_success:
    - cd causalml && fossa test
