name: causalml-rtd-py39
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - python=3.9
  - pandoc
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex<2.0.0
  - nbsphinx
  - pip:
    - cython==0.29.34
    - dill==0.3.8
    - importlib-metadata==8.5.0
    - joblib==1.4.0
    - lightgbm==4.5.0
    - matplotlib==3.9.2
    - multiprocess==0.70.16
    - numba==0.60.0
    - numpy==1.26.4
    - pandas==2.2.2
    - pygam==0.9.1
    - pyro-api==0.1.2
    - pyro-ppl==1.9.1
    - scikit-learn==1.5.2
    - scipy==1.11.4
    - seaborn==0.13.2
    - shap==0.46.0
    - statsmodels==0.14.2
    - xgboost==2.1.3
