name: Test conda-forge install

on: 
  push:
    paths:
      - 'envs/*.yml'
      - '.github/workflows/test-conda-forge-install.yml'

jobs:
  build:
    name: ${{ matrix.os }}-py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12']
        include:
          - python-version: '3.10'
            python-version-nd: '310'
          - python-version: '3.11'
            python-version-nd: '311'
          - python-version: '3.12'
            python-version-nd: '312'
          
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: causalml-py${{ matrix.python-version-nd }} 
          python-version: ${{ matrix.python-version }}

      - name: Install from conda-forge 
        run: |
            conda install -c conda-forge causalml
