name: Test conda-forge install

on: 
  push:
    paths:
      - 'envs/*.yml'
      - '.github/workflows/test-conda-forge-install.yml'

jobs:
  build:
    name: ${{ matrix.os }}-py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
        include:
          - python-version: 3.7
            python-version-nd: 37
          - python-version: 3.8
            python-version-nd: 38
          - python-version: 3.9
            python-version-nd: 39

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: create environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: causalml-py${{ matrix.python-version-nd }} 
          python-version: ${{ matrix.python-version }}

      - name: Install from conda-forge 
        run: |
            conda install -c conda-forge causalml
